services:
  mongo:
    image: mongo:5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: persons_db
    volumes:
      - ./exercise 3.1-3.22_Backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data_prod:/data/db
    container_name: my-app-mongo-prod
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    image: my-app-backend
    build:
      context: ./exercise 3.1-3.22_Backend
      dockerfile: Dockerfile
    container_name: my-app-prod
    depends_on:
      mongo:
        condition: service_healthy
  
  nginx:
    build:
      context: ./exercise 3.1-3.22_Frontend
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: my-app-nginx-reverse-proxy
    depends_on:
      - server

volumes:
  mongo_data_prod:
