services:
  app:
    image: my-app-frontend-dev
    build:
      context: ./exercise 3.1-3.22_Frontend 
      dockerfile: dev.Dockerfile 
    volumes:
      - ./exercise 3.1-3.22_Frontend:/usr/src/app
      - /usr/src/app/node_modules
    container_name: my-app-frontend-dev
    
  mongo:
    image: mongo:5
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: persons_db
    volumes:
      - ./exercise 3.1-3.22_Backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data_dev:/data/db
    container_name: my-app-mongo-dev

  server:
    image: my-app-backend-dev
    build:
      context: ./exercise 3.1-3.22_Backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./exercise 3.1-3.22_Backend:/usr/src/app
      - /usr/src/app/node_modules
    container_name: my-app-backend-dev
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
  
  nginx:
    image: nginx:1.28.1-alpine
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: my-app-reverse-proxy-dev
    depends_on:
      - app 
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

volumes:
  mongo_data_dev:
