services:
  app:
    image: todo-frontend-dev
    build:
      context: ./todo-frontend 
      dockerfile: dev.Dockerfile 
    volumes:
      - ./todo-frontend:/usr/src/app 
    container_name: todo-frontend-dev
  mongo:
    image: mongo:5
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    container_name: todo-mongo-dev

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes: 
      - ./todo-backend/redis_data:/data
    container_name: todo-redis-dev

  server:
    image: todo-backend-dev
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-backend:/usr/src/app
    container_name: todo-backend-dev
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://root:example@mongo:27017/the_database?authSource=admin
    depends_on:
      - mongo
      - redis
  
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

volumes:
  mongo_data: